server {
  listen 80;
  listen [::]:80;

  server_name mariooliveiradev.online www.mariooliveiradev.online;

  root /var/www/mariooliveiradev.online;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}
